AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation template file for Mastodon (Infrastructure layer).
Parameters:
  Tag1Key:
    Description: Tag key
    Type: String
  Tag1Value:
    Description: Tag value
    Type: String
  Tag2Key:
    Description: Tag key
    Type: String
  Tag2Value:
    Description: Tag value
    Type: String
  BlogFQDN:
    Description: FQDN for Blog
    Type: 'CommaDelimitedList'
  S3BlogBucketName:
    Description: S3 Bucket Name for blog
    Type: String
  AcmCertificateArn:
    Description: ACM Certificate ARN
    Type: String

Conditions:
  IsVirginia: !Equals 
    - !Ref 'AWS::Region'
    - us-east-1

Resources:
  BlogOriginAccessId:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: 'blog.fullstuck.net'

  BlogDistribution:
    Type: AWS::CloudFront::Distribution
    Properties: 
      DistributionConfig: 
        Aliases: 
          !Ref BlogFQDN
        Comment: 'fullstuck.net Blog site.'
        DefaultCacheBehavior:
          AllowedMethods: 
            - GET
            - HEAD
            - OPTIONS
          CachedMethods: 
            - GET
            - HEAD
            - OPTIONS
          Compress: true
          DefaultTTL: 300
          ForwardedValues: 
            QueryString: true
          MaxTTL: 86400
          MinTTL: 0
          TargetOriginId: !Ref S3BlogBucketName
          ViewerProtocolPolicy: 'redirect-to-https'
        DefaultRootObject: 'index.html'
        Enabled: true
        HttpVersion: http2
        IPV6Enabled: true
        Origins:
          - DomainName: !Sub "${S3BlogBucketName}.s3-website-us-east-1.amazonaws.com"
            CustomOriginConfig:
              OriginProtocolPolicy: http-only
            Id: !Ref S3BlogBucketName
            OriginPath: ''
        PriceClass: 'PriceClass_All'
        ViewerCertificate:
          AcmCertificateArn: !Ref AcmCertificateArn
          MinimumProtocolVersion: TLSv1.1_2016
          SslSupportMethod: sni-only
      Tags: 
        - Key: !Ref Tag1Key
          Value: !Ref Tag1Value
        - Key: !Ref Tag2Key
          Value: !Ref Tag2Value

Outputs:
  CloudFrontDomain:
    Description: CloudFront domain name
    Value: !GetAtt [ CloudFrontDistribution, DomainName ]